# Generated by Django 5.1.4 on 2024-12-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchase_qty_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_qty', models.FloatField(default=0)),
                ('sale_qty', models.FloatField(default=0)),
                ('total_bal_qty', models.FloatField()),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mobile', models.CharField(max_length=10)),
                ('customer_address', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('purchase', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchase')),
                ('sale', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.sale')),
            ],
        ),
    ]
