# Generated by Django 5.1.4 on 2024-12-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_customer_rename_unit_product_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '7. Customers'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': '5. Sales'},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='photo',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email_address',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
