# Generated by Django 5.1.4 on 2024-12-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_mymodel_alter_inventory_total_bal_qty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='total_bal_qty',
            new_name='Available_qty',
        ),
    ]
