# Generated by Django 5.1.4 on 2024-12-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_delete_mymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Available_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pur_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_qty',
            field=models.FloatField(default=0, null=True),
        ),
    ]
