# Generated by Django 5.1.4 on 2024-12-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_available_qty_product_pur_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Available_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pur_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_qty',
        ),
    ]
